spring:
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    consumer:
      enable-auto-commit: false
    properties: # for KafkaAvroDeserializer
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    listener:
      ack-mode: manual
  profiles:
    active: development

topics:
  example-data: example-data-topic
  retry-data: retry-topic
